### ISSUE TITLE
feat(firstname): As USER, I want a first name field, so that I can fill it in

### ISSUE THREAD

**Issue by mitni455** [mitni455/sca-dev-test#10]
###### Todo 
- [ ] `BDD acceptance criteria gherkins`
- [ ] `BDD Cucumber steps`
- [ ] `TDD UI tests with Enzyme`
- [ ] `TDD Unit tests with Jest`
- [ ] `Material Textfield`
- [ ] `Formik Textfield` 

###### Acceptance Criteria 
```
Feature: Register form firstname

Scenario: Firstname field mounted
  Given I am on the Homepage
  When the page is loaded  
  Then I should see the firstname field

Scenario: Valid Firstname field input
  Given I am on the Homepage
  When the input field has valid input 
  Then I should see no validation error 

Scenario: InValid Firstname field input
  Given I am on the Homepage
  When the input field has valid input 
  Then I should see a validation error
```
