### ISSUE TITLE
feat(FormLayout): As USER, I want a responsive register form layout, so that I can use it on all devices

### ISSUE THREAD

**Issue by mitni455** [mitni455/sca-dev-test#11]
###### Todo 
- [ ] `BDD acceptance criteria gherkins`
- [ ] `BDD Cucumber steps`
- [ ] `TDD UI tests with Enzyme`
- [ ] `TDD Unit tests with Jest`
- [ ] `install Material UI`
- [ ] `Install Formik`

###### Acceptance Criteria 
```
Feature: Register Form Layout

Scenario: Responsive layout for full screen
  Given I am on the Homepage
  When the window is full width 
  Then I should see the form visible

Scenario: Responsive layout for full screen
  Given I am on the Homepage
  When the window is laptop mode 
  Then I should see the form visible

Scenario: Responsive layout for tablet
  Given I am on the Homepage
  When the window is in tablet landscape mode
  Then I should see the form visible

Scenario: Responsive layout for tablet
  Given I am on the Homepage
  When the window is in tablet portrait mode
  Then I should see the form visible

Scenario: Responsive layou
