### ISSUE TITLE
feat(Homepage): As USER, I want a Homepage, so that I can mount the form

### ISSUE THREAD

**Issue by mitni455** [mitni455/sca-dev-test#4]
### Todo 
- [ ] `BDD acceptance criteria gherkins`
- [ ] `BDD Cucumber steps`
- [ ] `TDD UI tests with Enzyme`
- [ ] `TDD Unit tests with Jest`

### Acceptance Criteria 
```
Feature: Homepage

Scenario: Go to the Homepage
  Given I am on the Homepage
  Then I should see the form loaded
  And I should see the header 
```
