### ISSUE TITLE
feat(SubmissionPage): As a USER, I want a Subscription confirmation page, so that I can make sure I filled in the page correctly

### ISSUE THREAD

**Issue by mitni455** [mitni455/sca-dev-test#5]
### Todo 
- [ ] `BDD acceptance criteria gherkins`
- [ ] `BDD Cucumber steps`
- [ ] `TDD UI tests with Enzyme`
- [ ] `TDD Unit tests with Jest`

### Acceptance Criteria 
```
Feature: Submission Page 

Scenario: Go to the Submission Page
  Given I am on the Submission Page
  Then I should see confirmation message 
```
