### ISSUE TITLE
feat(phone): As USER, I want a Mobile phone field, so that I can fill it in

### ISSUE THREAD

**Issue by mitni455** [mitni455/sca-dev-test#7]
###### Todo 
- [ ] `BDD acceptance criteria gherkins`
- [ ] `BDD Cucumber steps`
- [ ] `TDD UI tests with Enzyme`
- [ ] `TDD Unit tests with Jest`
- [ ] `Material Textfield`
- [ ] `Formik Textfield` 

###### Acceptance Criteria 
```
Feature: Register form phone

Scenario: Mobile phone field mounted
  Given I am on the Homepage
  When the page is loaded  
  Then I should see the phone field

Scenario: Valid Mobile phone field input
  Given I am on the Homepage
  When the input field has valid input 
  Then I should see no validation error 

Scenario: InValid Mobile phone field input
  Given I am on the Homepage
  When the input field has valid input 
  Then I should see a validation error
```
